/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/info/': RouteRecordInfo<'/info/', '/info', Record<never, never>, Record<never, never>>,
    '/info/ahti': RouteRecordInfo<'/info/ahti', '/info/ahti', Record<never, never>, Record<never, never>>,
    '/info/hof': RouteRecordInfo<'/info/hof', '/info/hof', Record<never, never>, Record<never, never>>,
    '/info/jaska': RouteRecordInfo<'/info/jaska', '/info/jaska', Record<never, never>, Record<never, never>>,
    '/info/links': RouteRecordInfo<'/info/links', '/info/links', Record<never, never>, Record<never, never>>,
    '/info/saannot': RouteRecordInfo<'/info/saannot', '/info/saannot', Record<never, never>, Record<never, never>>,
    '/info/yleista': RouteRecordInfo<'/info/yleista', '/info/yleista', Record<never, never>, Record<never, never>>,
    '/jatkosarja': RouteRecordInfo<'/jatkosarja', '/jatkosarja', Record<never, never>, Record<never, never>>,
    '/joukkueet/': RouteRecordInfo<'/joukkueet/', '/joukkueet', Record<never, never>, Record<never, never>>,
    '/joukkueet/[id]': RouteRecordInfo<'/joukkueet/[id]', '/joukkueet/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/kyykka_admin': RouteRecordInfo<'/kyykka_admin', '/kyykka_admin', Record<never, never>, Record<never, never>>,
    '/ottelut/': RouteRecordInfo<'/ottelut/', '/ottelut', Record<never, never>, Record<never, never>>,
    '/ottelut/[id]': RouteRecordInfo<'/ottelut/[id]', '/ottelut/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pelaajat/': RouteRecordInfo<'/pelaajat/', '/pelaajat', Record<never, never>, Record<never, never>>,
    '/pelaajat/[id]': RouteRecordInfo<'/pelaajat/[id]', '/pelaajat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/runkosarja': RouteRecordInfo<'/runkosarja', '/runkosarja', Record<never, never>, Record<never, never>>,
    '/SuperWeekend': RouteRecordInfo<'/SuperWeekend', '/SuperWeekend', Record<never, never>, Record<never, never>>,
  }
}
