version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nkl
      - MYSQL_USER=nkladmin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  memcached:
    image: memcached
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
