# Generated by Django 5.1.1 on 2024-09-30 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('kyykka', '0001_initial'), ('kyykka', '0002_auto_20190319_0910'), ('kyykka', '0003_auto_20190324_2006'), ('kyykka', '0004_auto_20190325_1426'), ('kyykka', '0005_player'), ('kyykka', '0006_auto_20190328_1807'), ('kyykka', '0007_auto_20190402_2133'), ('kyykka', '0008_auto_20190402_2135'), ('kyykka', '0009_auto_20190402_2244'), ('kyykka', '0010_auto_20200107_0300'), ('kyykka', '0011_auto_20200112_1313'), ('kyykka', '0012_auto_20200114_0337'), ('kyykka', '0013_match_post_season'), ('kyykka', '0014_auto_20231119_1244'), ('kyykka', '0015_teamsinseason_bracket'), ('kyykka', '0016_auto_20231119_1454'), ('kyykka', '0017_auto_20231119_1504'), ('kyykka', '0018_auto_20231119_1624'), ('kyykka', '0019_auto_20231119_1734')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('no_brackets', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
            ],
            options={
                'verbose_name_plural': 'Current Season',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=99, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersInTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.team')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='TeamsInSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=128)),
                ('current_abbreviation', models.CharField(max_length=15)),
                ('players', models.ManyToManyField(through='kyykka.PlayersInTeam', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.team')),
                ('bracket', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('season', 'team')},
            },
        ),
        migrations.AddField(
            model_name='playersinteam',
            name='team_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyykka.teamsinseason'),
        ),
        migrations.AlterUniqueTogether(
            name='playersinteam',
            unique_together={('player', 'team_season')},
        ),
        migrations.RemoveField(
            model_name='playersinteam',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playersinteam',
            name='team',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('home_first_round_score', models.IntegerField(blank=True, null=True)),
                ('home_second_round_score', models.IntegerField(blank=True, null=True)),
                ('away_first_round_score', models.IntegerField(blank=True, null=True)),
                ('away_second_round_score', models.IntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='kyykka.teamsinseason')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='kyykka.teamsinseason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('field', models.IntegerField(blank=True, null=True)),
                ('post_season', models.BooleanField(default=False)),
                ('match_type', models.IntegerField(blank=True, null=True)),
                ('seriers', models.IntegerField(default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_round', models.IntegerField()),
                ('throw_turn', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.teamsinseason')),
                ('score_first', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('score_fourth', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('score_second', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('score_third', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
            ],
        ),
    ]
