# Generated by Django 3.1.3 on 2023-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20231119_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsinseason',
            name='bracket',
            field=models.IntegerField(null=True),
        ),
    ]
