# Generated by Django 3.1.3 on 2023-11-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_teamsinseason_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsinseason',
            name='current_name',
            field=models.CharField(max_length=128),
        ),
    ]
