# Generated by Django 3.1.3 on 2023-11-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20231119_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teamsinseason'),
        ),
    ]
