# Generated by Django 3.1.3 on 2024-09-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyykka', '0020_auto_20240901_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion', models.IntegerField(default=1)),
                ('throws', models.IntegerField(default=0)),
                ('misses', models.IntegerField(default=0)),
                ('vm_misses', models.IntegerField(default=0)),
                ('ones', models.IntegerField(default=0)),
                ('twos', models.IntegerField(default=0)),
                ('threes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('fives', models.IntegerField(default=0)),
                ('gte_six', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.IntegerField(default=0)),
                ('kyykat', models.IntegerField(default=0)),
                ('throws', models.IntegerField(default=0)),
                ('misses', models.IntegerField(default=0)),
                ('vm_misses', models.IntegerField(default=0)),
                ('nd_stats', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_position', to='kyykka.positionstats')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.playersinteam')),
                ('rd_stats', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_position', to='kyykka.positionstats')),
                ('st_stats', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_position', to='kyykka.positionstats')),
                ('th_stats', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourth_position', to='kyykka.positionstats')),
            ],
        ),
        migrations.AlterModelOptions(
            name='teamsinseason',
            options={'ordering': ('bracket', 'bracket_placement')},
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_matches', to='kyykka.teamsinseason'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_matches', to='kyykka.teamsinseason'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.season'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.match'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='throw',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.season'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.teamsinseason'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
