# Generated by Django 3.1.3 on 2024-09-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0021_auto_20240905_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionstats',
            old_name='postion',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='nd_stats',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='rd_stats',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='st_stats',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='th_stats',
        ),
        migrations.AddField(
            model_name='positionstats',
            name='seasons_stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='kyykka.seasonstats'),
            preserve_default=False,
        ),
    ]
