# Generated by Django 3.1.3 on 2024-09-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0022_auto_20240905_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionstats',
            options={'verbose_name_plural': 'Positions Stats'},
        ),
        migrations.AlterModelOptions(
            name='seasonstats',
            options={'verbose_name_plural': 'Seasons Stats'},
        ),
    ]
