# Generated by Django 3.1.3 on 2024-09-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0023_auto_20240905_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionstats',
            old_name='misses',
            new_name='pikes',
        ),
        migrations.RenameField(
            model_name='positionstats',
            old_name='vm_misses',
            new_name='zeros',
        ),
        migrations.RenameField(
            model_name='seasonstats',
            old_name='misses',
            new_name='pikes',
        ),
        migrations.RenameField(
            model_name='seasonstats',
            old_name='vm_misses',
            new_name='zeros',
        ),
    ]
