# Generated by Django 3.1.3 on 2024-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0024_auto_20240906_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='gte_six',
            field=models.IntegerField(default=0),
        ),
    ]
