# Generated by Django 3.1.3 on 2024-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0026_auto_20240906_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionstats',
            name='periods',
            field=models.IntegerField(default=0),
        ),
    ]
