# Generated by Django 3.1.3 on 2023-11-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyykka', '0013_match_post_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='seriers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='no_brackets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playersinteam',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamsInSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=128, unique=True)),
                ('current_abbreviation', models.CharField(max_length=15)),
                ('players', models.ManyToManyField(through='kyykka.PlayersInTeam', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.team')),
            ],
            options={
                'unique_together': {('season', 'team')},
            },
        ),
        migrations.AddField(
            model_name='playersinteam',
            name='team_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyykka.teamsinseason'),
        ),
        migrations.AlterUniqueTogether(
            name='playersinteam',
            unique_together={('player', 'team_season')},
        ),
        migrations.RemoveField(
            model_name='playersinteam',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playersinteam',
            name='team',
        ),
    ]
