# Generated by Django 3.1.3 on 2024-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyykka", "0020_auto_20240218_1745"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamsinseason",
            options={"ordering": ("bracket", "bracket_placement")},
        ),
        migrations.AddField(
            model_name="news",
            name="writer",
            field=models.TextField(default="Anon"),
        ),
    ]
