# Generated by Django 3.1.3 on 2025-01-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0020_auto_20241229_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='teamsinseason',
            options={'ordering': ('-season', 'bracket', 'bracket_placement')},
        ),
    ]
