# Generated by Django 3.1.3 on 2025-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0021_auto_20250113_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='score_first',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_fourth',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_second',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_third',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='throw_round',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='throw_turn',
            field=models.IntegerField(db_index=True),
        ),
    ]
