# Generated by Django 3.1.3 on 2025-01-20 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kyykka", "0022_auto_20250117_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsinseason",
            name="second_stage_bracket",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Runkosarja"),
                    (2, "Finaali"),
                    (3, "Pronssi"),
                    (4, "Välierä"),
                    (5, "Puolivälierä"),
                    (6, "Neljännesvälierä"),
                    (7, "Kahdeksannesvälierä"),
                    (8, "2. Kierros"),
                    (9, "1. Kierros"),
                    (10, "Runkosarjafinaali"),
                    (20, "Jumbofinaali"),
                    (31, "SuperWeekend: Alkulohko"),
                    (32, "SuperWeekend: Finaali"),
                    (33, "SuperWeekend: Pronssi"),
                    (34, "SuperWeekend: Välierä"),
                    (35, "SuperWeekend: Puolivälierä"),
                    (36, "SuperWeekend: Neljännesvälierä"),
                    (37, "SuperWeekend: Kahdeksannesvälierä"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="playoff_format",
            field=models.IntegerField(
                choices=[
                    (0, "Ei vielä päätetty / Undefined"),
                    (1, "Kiinteä 16 joukkueen Cup"),
                    (2, "Kiinteä 8 joukkueen Cup"),
                    (3, "Kiinteä 4 joukkueen Cup"),
                    (4, "Kiinteä 22 joukkueen Cup"),
                    (5, "1.Kierroksen Seedaus 6 joukkueen Cup"),
                    (6, "1.Kierroksen Seedaus 12 joukkueen Cup"),
                    (7, "SuperWeekend OKA seedaus 15 joukkueen Cup"),
                    (8, "Kiinteä 30 joukkueen Cup"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="superweekend",
            name="super_weekend_playoff_format",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Ei vielä päätetty / Undefined"),
                    (1, "Kiinteä 16 joukkueen Cup"),
                    (2, "Kiinteä 8 joukkueen Cup"),
                    (3, "Kiinteä 4 joukkueen Cup"),
                    (4, "Kiinteä 22 joukkueen Cup"),
                    (5, "1.Kierroksen Seedaus 6 joukkueen Cup"),
                    (6, "1.Kierroksen Seedaus 12 joukkueen Cup"),
                    (7, "SuperWeekend OKA seedaus 15 joukkueen Cup"),
                    (8, "Kiinteä 30 joukkueen Cup"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="throw",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
