# Generated by Django 3.1.3 on 2025-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0024_auto_20250126_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamsinseason',
            old_name='first_stage_bracket',
            new_name='second_stage_bracket',
        ),
        migrations.AlterUniqueTogether(
            name='teamsinseason',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teamsinseason',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_team_season'),
        ),
    ]
