# Generated by Django 3.1.3 on 2025-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0025_auto_20250126_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='video_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
