# Generated by Django 5.1.7 on 2025-03-29 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0026_auto_20250213_2247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(default='99', max_length=2),
        ),
        migrations.AlterField(
            model_name='playersinteam',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playersinteam',
            name='team_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.teamsinseason'),
        ),
    ]
