# Generated by Django 5.1.7 on 2025-11-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('kyykka', '0028_teamsinseason_logo_uploaded_at_and_more'), ('kyykka', '0029_alter_teamsinseason_logo_url'), ('kyykka', '0030_alter_teamsinseason_logo_url')]

    dependencies = [
        ('kyykka', '0027_alter_player_number_alter_playersinteam_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsinseason',
            name='logo_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Ei tyyppiä / Undefined'), (1, 'Runkosarja'), (2, 'Finaali'), (3, 'Pronssi'), (4, 'Välierä'), (5, 'Puolivälierä'), (6, 'Neljännesvälierä'), (7, 'Kahdeksannesvälierä'), (8, '2. Kierros'), (9, '1. Kierros'), (10, 'Runkosarjafinaali'), (11, 'Jatkosarja'), (20, 'Putoamiskarsinta'), (31, 'SuperWeekend: Alkulohko'), (32, 'SuperWeekend: Finaali'), (33, 'SuperWeekend: Pronssi'), (34, 'SuperWeekend: Välierä'), (35, 'SuperWeekend: Puolivälierä'), (36, 'SuperWeekend: Neljännesvälierä'), (37, 'SuperWeekend: Kahdeksannesvälierä')], null=True),
        ),
        migrations.AddField(
            model_name='teamsinseason',
            name='logo_url',
            field=models.ImageField(default='public/team_logos/default_team_logo.png', upload_to='public/team_logos/'),
        ),
    ]
