# Generated by Django 5.2.9 on 2026-03-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0028_match_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_player_accolade', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAccolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(blank=True, null=True)),
                ('placement', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (8, 'Top8'), (16, 'Top16'), (22, 'Top22'), (30, 'Top30')], null=True)),
                ('accolade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.accolade')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAccolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_team_name', models.CharField(blank=True, max_length=128, null=True)),
                ('placement', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (8, 'Top8'), (16, 'Top16'), (22, 'Top22'), (30, 'Top30')], null=True)),
                ('accolade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.accolade')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyykka.teamsinseason')),
            ],
        ),
    ]
