# Generated by Django 5.2.9 on 2026-03-09 09:43

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kyykka', '0029_accolade_playeraccolade_teamaccolade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='accolade',
            name='is_player_accolade',
        ),
        migrations.AddField(
            model_name='playeraccolade',
            name='status',
            field=models.TextField(choices=[('to_be_decided', 'To Be Decided'), ('not_played', 'Not Played'), ('unknown', 'Unknown'), ('unsure', 'Unsure'), ('resolved', 'Resolved')], default='resolved'),
        ),
        migrations.AddField(
            model_name='teamaccolade',
            name='status',
            field=models.TextField(choices=[('to_be_decided', 'To Be Decided'), ('not_played', 'Not Played'), ('unknown', 'Unknown'), ('unsure', 'Unsure'), ('resolved', 'Resolved')], default='resolved'),
        ),
        migrations.CreateModel(
            name='PairAccolade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('to_be_decided', 'To Be Decided'), ('not_played', 'Not Played'), ('unknown', 'Unknown'), ('unsure', 'Unsure'), ('resolved', 'Resolved')], default='resolved')),
                ('placement', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (8, 'Top8'), (16, 'Top16'), (22, 'Top22'), (30, 'Top30')], null=True)),
                ('accolade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.accolade')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.season')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='kyykka.userproxy')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='kyykka.userproxy')),
            ],
        ),
        migrations.AlterField(
            model_name='playeraccolade',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyykka.userproxy'),
        ),
        migrations.AlterField(
            model_name='playersinteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyykka.userproxy'),
        ),
        migrations.AlterField(
            model_name='teamsinseason',
            name='players',
            field=models.ManyToManyField(through='kyykka.PlayersInTeam', to='kyykka.userproxy'),
        ),
    ]
