# Generated by Django 5.2.9 on 2026-03-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0030_userproxy_remove_accolade_is_player_accolade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accolade',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyykka.userproxy'),
        ),
    ]
