# Generated by Django 5.1.7 on 2025-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0028_teamsinseason_logo_uploaded_at_and_more_squashed_0030_alter_teamsinseason_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsinseason',
            name='logo_url',
            field=models.ImageField(default='frontend/public/team_logos/default_team_logo.png', upload_to='frontend/public/team_logos/'),
        ),
    ]
